spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/webscraping
    username: andrea  
    password: italiano
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect 
        format_sql: true
server:
  port: 8080
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG 
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 